"""One-to-one spatial correspondence for evaluation; no ArcPy dependencies."""
import math

import numpy as np
from scipy.optimize import linear_sum_assignment
from scipy.spatial import cKDTree


def match_candidates(baseline_xy, variant_xy, radius, baseline_ids=None, variant_ids=None):
    """Match identities first (when supplied), then maximize pairs and minimize distance.

    IDs must represent stable identities, not sequential IDs regenerated by detection.
    Radius is inclusive. Independent connected components keep ordinary sparse
    candidate frames small; an excessively dense component fails explicitly.
    """
    radius = float(radius)
    if not math.isfinite(radius) or radius < 0:
        raise ValueError("Matching radius must be finite and nonnegative")
    frames = []
    for points in (baseline_xy, variant_xy):
        points = np.asarray(points, dtype=float)
        if points.shape == (0,):
            points = points.reshape(0, 2)
        if points.ndim != 2 or points.shape[1] != 2 or not np.isfinite(points).all():
            raise ValueError("Candidates must have finite XY coordinates with shape (n, 2)")
        frames.append(points)
    baseline, variant = frames
    ids = []
    for values, frame in zip((baseline_ids, variant_ids), frames):
        if values is not None:
            values = list(values)
            if len(values) != len(frame) or len(set(values)) != len(values):
                raise ValueError("Candidate IDs must be unique with one ID per coordinate")
        ids.append(values)
    forward = np.full(len(baseline), -1, dtype=int)
    reverse = np.full(len(variant), -1, dtype=int)
    edges = cKDTree(variant).query_ball_point(baseline, radius) if len(variant) else [[] for _ in baseline]
    back = [[] for _ in variant]
    for i, neighbors in enumerate(edges):
        for j in neighbors:
            back[j].append(i)
    ambiguous_baseline = sum(len(e) > 1 for e in edges)
    ambiguous_variant = sum(len(e) > 1 for e in back)
    if all(value is not None for value in ids):
        lookup = {key: j for j, key in enumerate(ids[1])}
        for i, key in enumerate(ids[0]):
            j = lookup.get(key)
            if j is not None and j in edges[i]:
                forward[i], reverse[j] = j, i
    visited = set()
    for first in range(len(baseline)):
        if first in visited or forward[first] >= 0:
            continue
        left, right, pending = set(), set(), [first]
        while pending:
            i = pending.pop()
            if i in left or forward[i] >= 0:
                continue
            left.add(i)
            for j in edges[i]:
                if reverse[j] < 0 and j not in right:
                    right.add(j)
                    pending.extend(back[j])
        visited.update(left)
        if not right:
            continue
        left, right = sorted(left), sorted(right)
        if len(left) * (len(right) + len(left)) > 4_000_000:
            raise ValueError("Candidate matching component is too dense; review radius/duplicates")
        # One unmatched edge costs more than every possible real distance combined.
        penalty = (min(len(left), len(right)) + 1) * (radius + 1)
        costs = np.full((len(left), len(right) + len(left)), penalty)
        costs[:, :len(right)] = 2 * penalty
        column = {j: k for k, j in enumerate(right)}
        for row, i in enumerate(left):
            for j in edges[i]:
                if j in column:
                    costs[row, column[j]] = np.linalg.norm(baseline[i] - variant[j])
        rows, columns = linear_sum_assignment(costs)
        for row, col in zip(rows, columns):
            if col < len(right) and costs[row, col] < penalty:
                i, j = left[row], right[col]
                forward[i], reverse[j] = j, i
    return {"baseline_to_variant": forward, "variant_to_baseline": reverse,
            "ambiguous_baseline": int(ambiguous_baseline), "ambiguous_variant": int(ambiguous_variant)}
